services:

  adservice:
    build: ./src/adservice
    ports:
      - "9555:9555"
    environment:
      - PORT=9555
      - DISABLE_STATS=1
      - DISABLE_TRACING=1
    restart: always

  redis-cart:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  currencyservice:
    build: ./src/currencyservice
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
    restart: always

  emailservice:
    build: ./src/emailservice
    ports:
      - "8082:8080"
    environment:
      - PORT=8080
    restart: always

  paymentservice:
    build: ./src/paymentservice
    ports:
      - "50051:50051"
    environment:
      - PORT=50051
    restart: always

  cartservice:
    build: ./src/cartservice/src
    ports:
      - "7070:7070"
    environment:
      - REDIS_ADDR=redis-cart:6379
      - PORT=7070
    depends_on:
      redis-cart:
        condition: service_healthy
    restart: always

  checkoutservice:
    build: ./src/checkoutservice
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - PAYMENT_SERVICE_ADDR=paymentservice:50051
      - EMAIL_SERVICE_ADDR=emailservice:8080
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
    depends_on:
      productcatalogservice:
        condition: service_started
      shippingservice:
        condition: service_started
      paymentservice:
        condition: service_started
      emailservice:
        condition: service_started
      currencyservice:
        condition: service_started
      cartservice:
        condition: service_started
    restart: always

  frontend:
    build: ./src/frontend
    ports:
      - "8085:8080"
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:8080
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
      - AD_SERVICE_ADDR=adservice:9555
    depends_on:
      productcatalogservice:
        condition: service_started
      currencyservice:
        condition: service_started
      cartservice:
        condition: service_started
      recommendationservice:
        condition: service_started
      shippingservice:
        condition: service_started
      checkoutservice:
        condition: service_started
      adservice:
        condition: service_started
    restart: always

  productcatalogservice:
    build: ./src/productcatalogservice
    ports:
      - "3550:3550"
    environment:
      - PORT=3550
    restart: always

  recommendationservice:
    build: ./src/recommendationservice
    ports:
      - "8083:8080"
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
    depends_on:
      productcatalogservice:
        condition: service_started
    restart: always

  shippingservice:
    build: ./src/shippingservice
    ports:
      - "50052:50051"
    environment:
      - PORT=50051
    restart: always

  loadgenerator:
    build: ./src/loadgenerator
    environment:
      - FRONTEND_ADDR=frontend:8080
      - USERS=10
      - RATE=1
    depends_on:
      frontend:
        condition: service_started
    restart: on-failure


