services:
  shoppingassistantservice:
    build: ./src/shoppingassistantservice
    ports:
      - "8084:8080"
    environment:
      - PORT=8080
      - PROJECT_ID=${PROJECT_ID:-demo-project}
      - REGION=${REGION:-us-central1}
      - ALLOYDB_DATABASE_NAME=${ALLOYDB_DATABASE_NAME:-boutique}
      - ALLOYDB_TABLE_NAME=${ALLOYDB_TABLE_NAME:-products}
      - ALLOYDB_CLUSTER_NAME=${ALLOYDB_CLUSTER_NAME:-boutique-cluster}
      - ALLOYDB_INSTANCE_NAME=${ALLOYDB_INSTANCE_NAME:-boutique-instance}
      - ALLOYDB_SECRET_NAME=${ALLOYDB_SECRET_NAME:-alloydb-password}
    restart: always