kind: Deployment
apiVersion: apps/v1
metadata:
  name: adservice-deploy
  namespace: {{ .Values.namespace }}
  labels:
    app: adservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
        - name: adservice
          image: docker.io/namanss/adservice:{{ .Values.adservice.imagetag }}
          ports:
            - containerPort: 9555
          env:
            - name: PORT
              value: "9555"
          resources:
            requests:
              memory: "100Mi"
              cpu: "300m"
            limits:
              memory: "300Mi"
              cpu: "300m"
---
kind: Service
apiVersion: v1
metadata:
    name: adservice
    namespace: {{ .Values.namespace }}
    labels:
        app: adservice
spec:
    selector:
        app: adservice
    ports:
        - protocol: TCP
          port: 9555
          targetPort: 9555
    type: {{ .Values.adservice.servicetype }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
    name: adservice
    namespace: {{ .Values.namespace }}