kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-deploy
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicasCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: namanss/frontend:{{ .Values.frontend.imagetag }}
          ports:
            - containerPort: 8080
          env:
          - name: PORT
            value: "8080"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: productcatalogservice-svc:3550
          - name: CURRENCY_SERVICE_ADDR
            value: currencyservice-svc:7000
          - name: CART_SERVICE_ADDR
            value: cartservice-svc:7070
          - name: RECOMMENDATION_SERVICE_ADDR
            value: recommendationservice-svc:8080
          - name: SHIPPING_SERVICE_ADDR
            value: shippingservice-svc:50051
          - name: CHECKOUT_SERVICE_ADDR
            value: checkoutservice-svc:5050
          - name: AD_SERVICE_ADDR
            value: adservice-svc:9555
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "400Mi"
              cpu: "400m"
---
kind: Service
apiVersion: v1
metadata:
  name: frontend-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: {{ .Values.frontend.servicetype }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: frontend-sa
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend