kind: Deployment
apiVersion: apps/v1
metadata:
  name: paymentservice-deploy
  namespace: {{ .Values.namespace }}
  labels:
    app: paymentservice
spec:
  replicas: {{ .Values.paymentservice.replicasCount }}
  strategy:
        type: {{ .Values.strategy.type }}
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: paymentservice
          image: namanss/paymentservice:{{ .Values.paymentservice.imagetag }}
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"
            - name: DISABLE_TRACING
              value: "true"
            - name: DISABLE_PROFILER
              value: "true"
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "300m"
---
kind: Service
apiVersion: v1
metadata:
  name: paymentservice-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: paymentservice
spec:
  selector:
    app: paymentservice
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: {{ .Values.paymentservice.servicetype }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: paymentservice-sa
  namespace: {{ .Values.namespace }}
  labels:
    app: paymentservice
