namespace: application

redisCart:
  replicasCount: 1
  imagetag: alpine
  servicetype: ClusterIP

adservice:
  replicasCount: 1
  imagetag: 11
  servicetype: ClusterIP

cartservice:
  replicasCount: 1
  imagetag: 14
  servicetype: ClusterIP

currencyservice:
  replicasCount: 1
  imagetag: 3
  servicetype: ClusterIP

emailservice:
  replicasCount: 1
  imagetag: 2
  servicetype: ClusterIP

paymentservice:
  replicasCount: 1
  imagetag: 1
  servicetype: ClusterIP

productcatalogservice:
  replicasCount: 1
  imagetag: 1
  servicetype: ClusterIP

shippingservice:
  replicasCount: 1
  imagetag: 1
  servicetype: ClusterIP

recommendationservice:
  replicasCount: 1
  imagetag: 1
  servicetype: ClusterIP